[package]
name = "fgbooks"
version = "0.5.5"
entrypoint = "lib.typ"
authors = ["FreelyGivenBooks"]
license = "CC0"
description = "Create an effectively laid out 5.5x8.5 print book."
categories = ["book"]

[template]
path = "template"
entrypoint = "main.typ"
# thumbnail = "thumbnail.png"
# https://github.com/typst/packages/blob/main/docs/manifest.md
